libckteec: fix spelling mistake
Fix spelling mistake in pkcs11_api.c.
Building in debug mode fails with the following error:

src/pkcs11_api.c: In function ‘C_Sign’:
src/pkcs11_api.c:969:36: error: ‘CKR_USER_NOT_LOGG_IN’ undeclared (first use in this function); did you mean ‘CKR_USER_NOT_LOGGED_IN’?
        CKR_SESSION_HANDLE_INVALID, CKR_USER_NOT_LOGG_IN,
                                    ^~~~~~~~~~~~~~~~~~~~

Fixes: 3f44b8702995 ("libckteec: add support for Signing and Verification Functions")
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Pengguang Zhu <zpghao@163.com>