libteec: refactor _dprintf()
GCC8.1 gives an error when compiling _dprintf():

src/teec_trace.c: In function ‘_dprintf’:
src/teec_trace.c:110:5: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 246 [-Werror=format-truncation=]
     "%s [%d] %s:%s:%d: %s",
     ^~~~~~~~~~~~~~~~~~~~~~
src/teec_trace.c:112:11:
     line, raw);
           ~~~
src/teec_trace.c:109:3: note: ‘snprintf’ output 11 or more bytes (assuming 266) into a destination of size 256
   snprintf(prefixed, MAX_PRINT_SIZE,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     "%s [%d] %s:%s:%d: %s",
     ~~~~~~~~~~~~~~~~~~~~~~~
     trace_level_strings[level], thread_id, prefix, func,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     line, raw);
     ~~~~~~~~~~

Fix this error by using a single output buffer, printing the prefix first
then the other arguments with the supplied format.

In addition, further simplify the function by getting rid of things that
do not make much sense:
- Remove the 'flen' parameter, which is only ever set to zero or
  strlen(__func__).
- Remove the TRACE_FUNC_LENGTH_CST macro which is not set by default and
  does not seem very useful.
- Change the return type to void because callers do not care about success
  or failure.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>