Add -Wunsafe-loop-optimizations only for gcc
Compiling with clang would fail with
```
error: unknown warning option '-Wunsafe-loop-optimizations'
```
Adjust CMake so that the warning is only added for GNU compiler.

Signed-off-by: Eero Aaltonen <eero.aaltonen@vaisala.com>
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>